package MainPackage;

import NetUtils.NetIntes;
import javax.swing.SwingWorker;

/**
 *
 * @author  OninJasper
 */
public class LocalMachineFrame extends javax.swing.JInternalFrame {

    /** Creates new form LocalMachineFrame */
    public LocalMachineFrame() {
        initComponents();
        InitialNetInteslList();
        getData();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelBasic = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNetInters = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNetInterData = new javax.swing.JList();
        jPanelIP = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaIPConfig = new javax.swing.JTextArea();
        jPanelRoute = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaRouteTable = new javax.swing.JTextArea();
        jPanelTCP = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaTCP = new javax.swing.JTextArea();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("This Device");

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Network Devices"));

        jListNetInters.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jListNetInters.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListNetInters.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListNetIntersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListNetInters);

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Other Information"));

        jListNetInterData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jListNetInterData.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListNetInterData);

        javax.swing.GroupLayout jPanelBasicLayout = new javax.swing.GroupLayout(jPanelBasic);
        jPanelBasic.setLayout(jPanelBasicLayout);
        jPanelBasicLayout.setHorizontalGroup(
            jPanelBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBasicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelBasicLayout.setVerticalGroup(
            jPanelBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBasicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Device Information", jPanelBasic);

        jScrollPane3.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("IP Configuration"));

        jTextAreaIPConfig.setColumns(20);
        jTextAreaIPConfig.setEditable(false);
        jTextAreaIPConfig.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextAreaIPConfig.setRows(5);
        jScrollPane3.setViewportView(jTextAreaIPConfig);

        javax.swing.GroupLayout jPanelIPLayout = new javax.swing.GroupLayout(jPanelIP);
        jPanelIP.setLayout(jPanelIPLayout);
        jPanelIPLayout.setHorizontalGroup(
            jPanelIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelIPLayout.setVerticalGroup(
            jPanelIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("IP Configuration", jPanelIP);

        jScrollPane4.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("List of Connected Device"));

        jTextAreaRouteTable.setEditable(false);
        jTextAreaRouteTable.setColumns(20);
        jTextAreaRouteTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextAreaRouteTable.setRows(5);
        jScrollPane4.setViewportView(jTextAreaRouteTable);

        javax.swing.GroupLayout jPanelRouteLayout = new javax.swing.GroupLayout(jPanelRoute);
        jPanelRoute.setLayout(jPanelRouteLayout);
        jPanelRouteLayout.setHorizontalGroup(
            jPanelRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRouteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRouteLayout.setVerticalGroup(
            jPanelRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRouteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Connected Device", jPanelRoute);

        jScrollPane5.setBorder(null);
        jScrollPane5.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Active TCP Connection"));

        jTextAreaTCP.setEditable(false);
        jTextAreaTCP.setColumns(20);
        jTextAreaTCP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextAreaTCP.setRows(5);
        jTextAreaTCP.setBorder(null);
        jScrollPane5.setViewportView(jTextAreaTCP);

        javax.swing.GroupLayout jPanelTCPLayout = new javax.swing.GroupLayout(jPanelTCP);
        jPanelTCP.setLayout(jPanelTCPLayout);
        jPanelTCPLayout.setHorizontalGroup(
            jPanelTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTCPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTCPLayout.setVerticalGroup(
            jPanelTCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTCPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Active Connection", jPanelTCP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListNetIntersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListNetIntersValueChanged
        ShowNetIntersData();
    }//GEN-LAST:event_jListNetIntersValueChanged

    /** Find local network interface devices */
    public void InitialNetInteslList()
    {
        try {
            jListNetInters.setListData(NetIntes.getListNetIntesNames());
        } catch (Exception e) {}        
    }
    
    /** Display data of selected network interface */
    public void ShowNetIntersData()
    {
        try {
            int index = jListNetInters.getSelectedIndex();
            jListNetInterData.setListData(NetIntes.getNetInteDataByIndex(index));
        } catch (Exception e) {}           
    }
    
  
    public void getData()
    {  
        new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {  
                jTabbedPane1.setTitleAt(3, "Active Connection [Loading ...]");
                Utilities.executeCmd(jTextAreaTCP, "netstat -anot 5 -p TCP");    
                jTabbedPane1.setTitleAt(3, "TCP Infos & Stats");
                throw new UnsupportedOperationException("Not supported yet.");
            }
        }.execute(); 
        
        new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {   
                jTabbedPane1.setTitleAt(1, "IP Configuration [Loading ...]");                
                Utilities.executeCmd(jTextAreaIPConfig, "nmap -sn --traceroute 192.168.0.*");    
                jTabbedPane1.setTitleAt(1, "IP Configuration");                
                throw new UnsupportedOperationException("Not supported yet.");
            }
        }.execute(); 
        
        new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {  
                jTabbedPane1.setTitleAt(2, "Listed Device [Loading ...]");
                Utilities.executeCmd(jTextAreaRouteTable, "nmap -sP 192.168.0.1/24");    
                jTabbedPane1.setTitleAt(2, "Listed Device");
                throw new UnsupportedOperationException("Not supported yet.");
            }
        }.execute();     
    }  
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jListNetInterData;
    private javax.swing.JList jListNetInters;
    private javax.swing.JPanel jPanelBasic;
    private javax.swing.JPanel jPanelIP;
    private javax.swing.JPanel jPanelRoute;
    private javax.swing.JPanel jPanelTCP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaIPConfig;
    private javax.swing.JTextArea jTextAreaRouteTable;
    private javax.swing.JTextArea jTextAreaTCP;
    // End of variables declaration//GEN-END:variables
}
