package MainPackage;

import Components.*;
import firewall.*;
import firewall.Firewall;
import java.net.InetAddress;
import java.net.UnknownHostException;
import NetUtils.IPAddress;
import NetUtils.*;
import ScanObjects.ObjectsList;
import java.util.Enumeration;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.beans.*;
import java.io.File;
import java.util.Arrays;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.beans.binding.Bindings.not;
import javax.swing.event.*;

/*
 * MainFrame.java
 *
 */

/**
 *
 * @author  JasperOnin
 */

public class MainFrame extends javax.swing.JFrame {

    public static DefaultListModel objectModel;
    
    public ObjectFrame of;

    /** Creates new form MainFrame */
    public MainFrame() {
       
        initComponents();
        objectModel = new DefaultListModel();  
        jListObjects.setModel(objectModel); 
        SetIcon();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        jMenuItemShow = new javax.swing.JMenuItem();
        jMenuItemHide = new javax.swing.JMenuItem();
        jMenuItemRemove = new javax.swing.JMenuItem();
        jSplitPane = new javax.swing.JSplitPane();
        jScrollPaneObjects = new javax.swing.JScrollPane();
        jListObjects = new javax.swing.JList();
        jScrollPaneRight = new javax.swing.JScrollPane();
        jDesktopPane = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        jAOMenuItem = new javax.swing.JMenuItem();
        jMenuItemTrace = new javax.swing.JMenuItem();
        jMenuItemMsg = new javax.swing.JMenuItem();
        jExitMenuItem = new javax.swing.JMenuItem();
        jObjectsMenu = new javax.swing.JMenu();
        jLMMenuItem = new javax.swing.JMenuItem();
        jAboutMenu = new javax.swing.JMenu();
        jAboutMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItemShow.setText("Show");
        jMenuItemShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemShowActionPerformed1(evt);
            }
        });
        jPopupMenu.add(jMenuItemShow);

        jMenuItemHide.setText("Hide");
        jMenuItemHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHideActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemHide);

        jMenuItemRemove.setText("Remove");
        jMenuItemRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoveActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemRemove);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JaspersKey");
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));
        setLocationByPlatform(true);
        setResizable(false);

        jSplitPane.setDividerLocation(150);
        jSplitPane.setDividerSize(8);
        jSplitPane.setOneTouchExpandable(true);

        jScrollPaneObjects.setBorder(javax.swing.BorderFactory.createTitledBorder("Scanned Item"));

        jListObjects.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListObjects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListObjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListObjectsMouseClicked(evt);
            }
        });
        jListObjects.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jListObjectsKeyPressed(evt);
            }
        });
        jScrollPaneObjects.setViewportView(jListObjects);

        jSplitPane.setLeftComponent(jScrollPaneObjects);

        jScrollPaneRight.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPaneRight.setMinimumSize(new java.awt.Dimension(80, 80));
        jScrollPaneRight.setPreferredSize(new java.awt.Dimension(40, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jDesktopPane.add(jScrollPane1);
        jScrollPane1.setBounds(450, -40, 166, 40);

        jScrollPaneRight.setViewportView(jDesktopPane);

        jSplitPane.setRightComponent(jScrollPaneRight);

        jFileMenu.setText("Action");
        jFileMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFileMenuMouseClicked(evt);
            }
        });

        jAOMenuItem.setText("Network Scan");
        jAOMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAOMenuItemActionPerformed(evt);
            }
        });
        jFileMenu.add(jAOMenuItem);

        jMenuItemTrace.setText("Network Assessment");
        jMenuItemTrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraceActionPerformed(evt);
            }
        });
        jFileMenu.add(jMenuItemTrace);

        jMenuItemMsg.setText("Protect Network");
        jMenuItemMsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemMsgMouseClicked(evt);
            }
        });
        jMenuItemMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMsgActionPerformed(evt);
            }
        });
        jFileMenu.add(jMenuItemMsg);

        jExitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jExitMenuItem.setText("Exit");
        jExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jFileMenu.add(jExitMenuItem);

        jMenuBar.add(jFileMenu);

        jObjectsMenu.setText("View");

        jLMMenuItem.setText("This Machine");
        jLMMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLMMenuItemActionPerformed(evt);
            }
        });
        jObjectsMenu.add(jLMMenuItem);

        jMenuBar.add(jObjectsMenu);

        jAboutMenu.setText("About");

        jAboutMenuItem.setText("About JaspersKey");
        jAboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jAboutMenu.add(jAboutMenuItem);

        jMenuBar.add(new WindowMenu(jDesktopPane));

        jMenuBar.add(jAboutMenu);

        jMenu1.setText("Help");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        jMenuItem1.setText("Get Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed1(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("How to use Scan by IP Address");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed1(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AboutJFrame.main(null);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItemShowActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemShowActionPerformed1
        ShowObjectFrame();
}//GEN-LAST:event_jMenuItemShowActionPerformed1

    private void jMenuItemHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHideActionPerformed
        HideObjectFrame();
    }//GEN-LAST:event_jMenuItemHideActionPerformed

    private void jMenuItemRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoveActionPerformed
        RemoveObject();
    }//GEN-LAST:event_jMenuItemRemoveActionPerformed

    private void jLMMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLMMenuItemActionPerformed
        ShowLocalMachineFrame();
    }//GEN-LAST:event_jLMMenuItemActionPerformed

    private void jAOMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAOMenuItemActionPerformed
        InetAddress ip;
        String hostname;
        int selection = JOptionPane.showOptionDialog(null, "Please Select an Option","Network Scan",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE, null, 
                new String[]{"Scan Current Network", "Scan by IP Address"},"");
        
           
            if(selection==0){
              test t = new test();
              t.setLocationRelativeTo(null);
              t.setVisible(true);
            }
            else{
            AddObjectDialog.main(null);
            }
            
    }//GEN-LAST:event_jAOMenuItemActionPerformed

    private void jMenuItemTraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraceActionPerformed
      
        assessmentJFrame.main(null);
    }//GEN-LAST:event_jMenuItemTraceActionPerformed

    private void jMenuItemMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMsgActionPerformed
    NetworkProtect np = new NetworkProtect();
        try{
            Utilities.executeNetSh();}
         catch (InterruptedException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                 }
       np.setVisible(true);
        
         
        
    }//GEN-LAST:event_jMenuItemMsgActionPerformed

    private void jListObjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListObjectsMouseClicked
         if (evt.getButton() == MouseEvent.BUTTON3)  // Right Mouse Click
            ShowObjectsPopupMenu(evt.getX(), evt.getY());
        if (evt.getClickCount() == 2)   // Double Mouse Click
            ShowObjectFrame();
}//GEN-LAST:event_jListObjectsMouseClicked

    private void jListObjectsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListObjectsKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_DELETE) // Pressing Del buttom
            RemoveObject();
        if (key == KeyEvent.VK_ENTER) // Pressing Enter buttom
            ShowObjectFrame();
}//GEN-LAST:event_jListObjectsKeyPressed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
   
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed1
    helpJFrame hj = new helpJFrame();
     hj.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed1

    private void jMenuItem2ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed1
         helpAssessForm ha = new helpAssessForm();
         ha.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed1

    private void jMenuItemMsgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemMsgMouseClicked
        try {
            Utilities.executeNetSh();
        } catch (InterruptedException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_jMenuItemMsgMouseClicked

    private void jFileMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFileMenuMouseClicked
        // TODO add your handling code here        
    }//GEN-LAST:event_jFileMenuMouseClicked

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    public void AddObjectFrame(String title)
    {
        of = new ObjectFrame(title, this); 
        of.setTitle(title);
        of.setVisible(true);
        jDesktopPane.add(of);
        try {
            of.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}             
    }
    
    public void AddLocalMachineFrame()
    {
        LocalMachineFrame lm = new LocalMachineFrame(); 
        lm.setVisible(true);
        jDesktopPane.add(lm);
        try {
            lm.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}      
    }
    
    public void ShowLocalMachineFrame()
    {  
        String object = "Local Machine";
        for (JInternalFrame frame : jDesktopPane.getAllFrames())
            if (frame.getTitle().equals(object))
            {
                try {
                    frame.setSelected(true);
                } catch (java.beans.PropertyVetoException e) {return;}             
                return; 
            }
        AddLocalMachineFrame();
    }

    public void ShowObjectFrame()
    {
        String object = getSelectedElement(jListObjects);
        if (!IPAddress.validObject(object)) return;
        for (JInternalFrame frame : jDesktopPane.getAllFrames())
            if (frame.getTitle().equals(object))
            {
                try {
                    frame.setSelected(true);                 
                } catch (java.beans.PropertyVetoException e) {return;}    
                return;
            }
        AddObjectFrame(object);        
    }
    
    public void HideObjectFrame()
    {
        String object = getSelectedElement(jListObjects);
        for (JInternalFrame frame : jDesktopPane.getAllFrames())
            if (frame.getTitle().equals(object))
                try
                {
                    frame.setClosed(true);
                } catch (java.beans.PropertyVetoException e) {}        
    }
    
    public void RemoveObject()
    {
        String object = getSelectedElement(jListObjects);
        if (object == null) return;     
        if (!IPAddress.validObject(object)) return;
        
        int choice = JOptionPane.showConfirmDialog(MainFrame.this, 
            "Are you sure you want to delete this scanned IP: " + object + "?", "Scaned IP address", 
            JOptionPane.OK_CANCEL_OPTION );
        if (choice != JOptionPane.OK_OPTION) return;
        
        HideObjectFrame();
        
        objectModel.remove(jListObjects.getSelectedIndex());            
        ObjectsList.removeObject(object);
    }
    
    public static Vector getElements(DefaultListModel model)
    {       
        Enumeration enumeration = model.elements();
        Vector<String> vector = new Vector<String>();
        while (enumeration.hasMoreElements())
            vector.add(enumeration.nextElement().toString());
        return vector;
    } 
 
    public static void AddNewElement(JList list, DefaultListModel model, String object)
    {
        model.addElement(object);
        list.requestFocus();
    }
    
    public void SetIcon(){
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Ampeross-Qetto-2-Security.png")));
    }
    public void ShowObjectsPopupMenu(int x, int y)
    {
        // Get mouse posiiton
        jListObjects.getCellBounds(x, x);
            
        // Show Popup Menu at the selected item
        String object = getSelectedElement(jListObjects);
        if (!IPAddress.validObject(object)) return;
        jPopupMenu.show(jListObjects, x, y);        
    }              
    
    public static String getSelectedElement(JList list)
    {
        try {
            return list.getSelectedValue().toString();        
        }
        catch (Exception e)
        {
            return "";
        }
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAOMenuItem;
    private javax.swing.JMenu jAboutMenu;
    private javax.swing.JMenuItem jAboutMenuItem;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuItem jExitMenuItem;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JMenuItem jLMMenuItem;
    public static javax.swing.JList jListObjects;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemHide;
    private javax.swing.JMenuItem jMenuItemMsg;
    private javax.swing.JMenuItem jMenuItemRemove;
    private javax.swing.JMenuItem jMenuItemShow;
    private javax.swing.JMenuItem jMenuItemTrace;
    private javax.swing.JMenu jObjectsMenu;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneObjects;
    private javax.swing.JScrollPane jScrollPaneRight;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}